language: python

services:
  - postgresql

before_script:
  - psql -c 'create database paranoid;' -U postgres

env:
  - DATABASE_URL=postgres://localhost/paranoid

python:
  - "3.5"
  - "3.6"
  - "3.7"

script:
  - python setup.py test
